# Generated by Django 5.1.6 on 2025-03-10 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='Users.user'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='Users.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('patients', 'Patients'), ('companions', 'Companions')], default='companions', max_length=20),
        ),
    ]
