# Generated by Django 5.1.6 on 2025-05-17 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_companion_profile_photo_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='Users.patient'),
        ),
    ]
