# Generated by Django 5.1.6 on 2025-05-29 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_companion_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='companion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Users.companion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
