# Generated by Django 5.0.1 on 2025-06-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_task_companion_task_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='companion',
            name='last_sos_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companion',
            name='sos_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_sos_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sos_alert',
            field=models.BooleanField(default=False),
        ),
    ]
